### ISSUE TITLE
Cannot set property length of [object Object] Error

### ISSUE THREAD

**Issue by abhisekp** [dtao/console-highlight#3]
``` sh
/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/bail/index.js:28
        throw err;
        ^

TypeError: Cannot set property length of [object Object] which has only a getter
    at [object Object].core.Node.insertBefore (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/jsdom/lib/jsdom/level1/core.js:553:30)
    at [object Object].<anonymous> (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/jsdom/lib/jsdom/level2/events.js:332:20)
    at [object Object].proto.(anonymous function) [as insertBefore] (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/jsdom/lib/jsdom/utils.js:23:26)
    at [object Object].core.Node.appendChild (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/jsdom/lib/jsdom/level1/core.js:671:17)
    at [object Object].textContent (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/jsdom/lib/jsdom/level3/core.js:187:10)
    at /home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/htmlout/htmlout.js:94:27
    at Array.forEach (native)
    at htmlout (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/htmlout/htmlout.js:92:15)
    at htmlout (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/htmlout/htmlout.js:116:12)
    at consoleHighlight (/home/abhisekp/MyProjects/NodeApp/md-urls/node_modules/console-highlight/consoleHighlight.js:20:10)
```
### My Code

``` js
import highlight from 'console-highlight';
console.log(highlight('// what the hell'));

```

**Comment by marcosc90** [comment]
+1 This is happening to me aswell.

**Comment by abhisekp** [comment]
@marcosc90 the Latest commit `231f65c` was on 5th Mar 2014.

Looks like this is no longer maintained. :pensive: 
Too bad... too sad :cry:
